---
- name: Deploy Grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
