---
- name: Deploy Uptime Kuma
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma
    state: started
    restart_policy: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
