---
- name: Add Tailscale apt key
  become: true
  shell: curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
  args:
    executable: /bin/bash

- name: Add Tailscale apt repository
  become: true
  shell: curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list | tee /etc/apt/sources.list.d/tailscale.list
  args:
    executable: /bin/bash

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Tailscale
  apt:
    name: tailscale
    state: present

- name: Start and authenticate Tailscale
  command: "tailscale up --authkey={{ TAILSCALE_AUTH_KEY }}"