---
- name: Deploy Portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
