---
- name: Deploy Nginx Proxy Manager
  docker_container:
    name: nginx_proxy_manager
    image: jc21/nginx-proxy-manager:latest
    state: started
    restart_policy: always
    ports:
      - "8080:80"
      - "81:81"
      - "4343:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    env:
      ADMIN_EMAIL: "{{ NPM_ADMIN_EMAIL }}"
      ADMIN_PASSWORD: "{{ NPM_ADMIN_PASSWORD }}"