---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true
